[package]
name = "vue-rocket"
version = "0.1.0"
authors = ["DiscreetProtein <jordan@clearbluetechnologies.com>"]

[dependencies]
rocket = "0.3.7"
rocket_codegen = "0.3.7"
serde = "1.0.37"
serde_derive = "1.0.37"
serde_json = "1.0.13"
rocket_cors = "0.2.3"
